#!/usr/bin/env python3

import urllib.request, urllib.parse, json, sys

#http://www.datamuse.com/api/


version_id = '0.0.1'
divider = '************************************************************************************'
spacer = '*'

class term_colors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


def define_req(data_dict):
    response = []
    if len(data_dict['wordlist']) > 0:
        word = data_dict['wordlist'][0]
        params = '?' + 'sp=' + word + '&md=d'
        call = call_api(params)


        response.extend([divider,spacer])
        response.append('* ' + term_colors.HEADER + term_colors.BOLD + word + ' is defined as:' + term_colors.ENDC)
        response.extend([spacer,divider,spacer,spacer])
        if call and 'defs' in call[0]:
            for index, item in enumerate(call[0]['defs']):
                ind_to_cut = item.find("\t")
                response.append('* ' + term_colors.OKGREEN + str(index + 1) + '. ' + term_colors.ENDC + item[ind_to_cut:])
            response.extend([spacer,spacer,divider])
            return response
        else:
            response.append('* ' + term_colors.WARNING + 'There were no matches for your query' + term_colors.ENDC)
            response.extend([spacer,spacer,divider,'\n\n'])
            return response
    print_error('INPUT ERROR: Define must include a word to look up\n    See: words --help')
    return response


def lookup_req(data_dict):
    valid_options = {'means':'ml','max':'max','spelled':'sp','sounds':'sl','topics':'topics'}
    params = '?'
    max_declared = False
    for item in data_dict['options']:
        params += valid_options[item[0]]
        params += '=' + item[1] + '&'
        if item[0] == 'max':
            max = True
    if not max_declared:
        params += 'max=10&'
    call = call_api(params[:-1])

    response = []
    response.extend(['\n\n',divider,spacer])
    response.append('* ' +  + term_colors.HEADER + term_colors.BOLD + 'The following words match yout query:' + term_colors.ENDC)
    response.extend([spacer,divider,spacer,spacer])
    if call:
        for index, item in enumerate(call):
            response.append('* ' + str(index + 1) + '. ' + item['word'])
        response.extend([spacer,spacer,divider,'\n\n'])
        return response
    response.append('* '+ term_colors.WARNING + 'There were no matches for your query' + term_colors.ENDC)
    response.extend([spacer,spacer,divider,'\n\n'])
    return response


def call_api(query_string):
    dmapi = 'http://api.datamuse.com/words'
    url = dmapi + query_string
    req = urllib.request.Request(url,method='GET')

    with urllib.request.urlopen(req, timeout=5) as res:
        value = res.read().decode('ASCII')
        value = json.loads(str(value))
        return value or False

def validate_operation(op):
    if op in valid_args:
        return False
    return True

def print_error(msg):
    error = term_colors.FAIL
    error += term_colors.BOLD
    error += msg
    error += term_colors.ENDC
    print('\n\n' + error + '\n\n')

def display_help():
    print('''\033[95m\033[1m
        words:\033[0m

        a utility for retrieving word information from the datamuse api

        \033[95m\033[1m
        usage:\033[0m

        words define [ word ]
        words lookup [ ... options ... ]

        \033[95m\033[1m
        examples:\033[0m

        words lookup --max="10" --spelled="*ding" --means="joining merging tying"
        words lookup --topics="weather clouds" --sounds="rimbus"
        words define celebratory
        words define redolent


        \033[95m\033[1m
        operators:\033[0m

        lookup              initiate a lookup

        define              get a word definition

        help, -h, --help    display this help information

        version, -v,        display the current words version id
        --version


        \033[95m\033[1m
        options:\033[0m

            these take the form of quoted integers or space delimited strings:


        --max=" ... "       [int]:    number of results to return (default: 10).
                                      can only be used in combination with other
                                      options

        --spelled=" ... "   [string]: require that results be spelled like this string
                                      accepts '*' as a multi-character wildcard & '?'
                                      as single character wildcard -single word

        --means=" ... "     [string]: require that the results have a meaning
                                      related to this string value -space delimited

        --sounds=" ... "    [string]: require that the results are pronounced similarly
                                      to this string of characters -single word

        --topics=" ... "    [string]: results will be skewed toward these topics
                                      space delimited
    ''')

def display_version(id):
    print('Words, Version: ' + id)


def parse_args():
    args = sys.argv[1:]
    query = {}
    if len(args) < 1:
        print_error('INPUT ERROR: At least one operator must be provided\n    See: words --help\n')
        return False

    query['operation'] = args.pop(0)
    if query['operation'] in ['help','-h','--help']:
        display_help()
        return False
    elif query['operation'] in ['version','-v','--version']:
        display_version(version_id)
        return False
    elif query['operation'] in ['lookup','define']:
        query['wordlist'] = []
        query['options'] = []
        for val in args:
            if val[0:2] == '--':
                op_list = val.split('=')
                op_list[0] = op_list[0][2:]
                op_list[1] = op_list[1].replace(' ','+')
                query['options'].append(op_list)
            else:
                query['wordlist'].append(val)
        return query
    else:
        print_error('INPUT ERROR: Invalid operator or syntax.\n    See: words --help')
        return False


if __name__ == '__main__':
    instructions = parse_args()
    if instructions:
        if instructions['operation'] == 'define':
            response = define_req(instructions)
        elif instructions['operation'] == 'lookup':
            response = lookup_req(instructions)
        else:
            print_error('INPUT ERROR: Unknown operator ' + instructions['operation'])
            response = ''
        for item in response:
            print(item)
